export { default } from "./../../_gen/openfl/utils/AssetLibrary";

import { default as FilterType } from "../../_gen/swf/exporters/core/FilterType";
import { default as ShapeCommand } from "../../_gen/swf/exporters/core/ShapeCommand";
import { default as SWFLiteLibrary } from "../../_gen/swf/exporters/swflite/SWFLiteLibrary";
import { default as BitmapSymbol } from "../../_gen/swf/exporters/swflite/BitmapSymbol";
import { default as ButtonSymbol } from "../../_gen/swf/exporters/swflite/ButtonSymbol";
import { default as DynamicTextSymbol } from "../../_gen/swf/exporters/swflite/DynamicTextSymbol";
import { default as FontSymbol } from "../../_gen/swf/exporters/swflite/FontSymbol";
import { default as ShapeSymbol } from "../../_gen/swf/exporters/swflite/ShapeSymbol";
import { default as SpriteSymbol } from "../../_gen/swf/exporters/swflite/SpriteSymbol";
import { default as StaticTextRecord } from "../../_gen/swf/exporters/swflite/StaticTextRecord";
import { default as StaticTextSymbol } from "../../_gen/swf/exporters/swflite/StaticTextSymbol";
import { default as SWFSymbol } from "../../_gen/swf/exporters/swflite/SWFSymbol";
import { default as Frame } from "../../_gen/swf/exporters/swflite/timeline/Frame";
import { default as FrameObject } from "../../_gen/swf/exporters/swflite/timeline/FrameObject";
import { default as FrameObjectType } from "../../_gen/swf/exporters/swflite/timeline/FrameObjectType";
import { default as AnimateBitmapSymbol } from "../../_gen/swf/exporters/animate/AnimateBitmapSymbol";
import { default as AnimateButtonSymbol } from "../../_gen/swf/exporters/animate/AnimateButtonSymbol";
import { default as AnimateDynamicTextSymbol } from "../../_gen/swf/exporters/animate/AnimateDynamicTextSymbol";
import { default as AnimateFontSymbol } from "../../_gen/swf/exporters/animate/AnimateFontSymbol";
import { default as AnimateFrame } from "../../_gen/swf/exporters/animate/AnimateFrame";
import { default as AnimateFrameObject } from "../../_gen/swf/exporters/animate/AnimateFrameObject";
import { default as AnimateFrameObjectType } from "../../_gen/swf/exporters/animate/AnimateFrameObjectType";
import { default as AnimateLibrary } from "../../_gen/swf/exporters/animate/AnimateLibrary";
import { default as AnimateLoader } from "../../_gen/swf/exporters/animate/AnimateLoader";
import { default as AnimateShapeCommand } from "../../_gen/swf/exporters/animate/AnimateShapeCommand";
import { default as AnimateShapeSymbol } from "../../_gen/swf/exporters/animate/AnimateShapeSymbol";
import { default as AnimateSpriteSymbol } from "../../_gen/swf/exporters/animate/AnimateSpriteSymbol";
import { default as AnimateStaticTextSymbol } from "../../_gen/swf/exporters/animate/AnimateStaticTextSymbol";
import { default as AnimateSymbol } from "../../_gen/swf/exporters/animate/AnimateSymbol";
import { default as AnimateTimeline } from "../../_gen/swf/exporters/animate/AnimateTimeline";

// Apart from adding this file to the sideEffects array in package.json, we also need
// to list each class out here so that it is included in the webpack bundle
FilterType;
ShapeCommand;
SWFLiteLibrary;
BitmapSymbol;
ButtonSymbol;
DynamicTextSymbol;
FontSymbol;
ShapeSymbol;
SpriteSymbol;
StaticTextRecord;
StaticTextSymbol;
SWFSymbol;
Frame;
FrameObject;
FrameObjectType;
AnimateBitmapSymbol;
AnimateButtonSymbol;
AnimateDynamicTextSymbol;
AnimateFontSymbol;
AnimateFrame;
AnimateFrameObject;
AnimateFrameObjectType;
AnimateLibrary;
AnimateLoader;
AnimateShapeCommand;
AnimateShapeSymbol;
AnimateSpriteSymbol;
AnimateStaticTextSymbol;
AnimateSymbol;
AnimateTimeline;